# Weekly Population Projections 2020-2025

In [1]:
import pandas as pd
import numpy as np

In [2]:
constants = pd.read_excel("../../data/raw/pob_anual.xlsx", sheet_name="constants")

In [3]:
constants.head()

   codigo        canton         r             n0        t
0     101      San José  0.001868  347692.458565  0.09434
1     102        Escazú  0.003153   69342.771863  0.09434
2     103  Desamparados  0.003087  238762.282323  0.09434
3     104      Puriscal  0.002967   38240.587051  0.09434
4     105       Tarrazú  0.001080   17842.632765  0.09434

In [9]:
semanas_2019 = [f"2019-{i}" for i in range(27, 54)]
semanas = semanas_2019 + [f"2020-{i}" for i in range(1, 54)]
semanas = semanas + [f"2021-{i}" for i in range(1, 54)]
semanas = semanas + [f"2022-{i}" for i in range(1, 54)]
semanas = semanas + [f"2023-{i}" for i in range(1, 54)]
semanas = semanas + [f"2024-{i}" for i in range(1, 54)]
semanas = semanas + [f"2024-{i}" for i in range(1, 54)]
semanas = semanas + [f"2025-{i}" for i in range(1, 54)]

In [10]:
for i in range(len(semanas)):
    constants[semanas[i]] = constants["n0"] * np.exp(constants["r"] * (constants["t"] + i / 53 + 2/53))

In [11]:
constants.head()

,codigo,canton,r,n0,t,2019-27,2019-28,2019-29,2019-30,2019-31,...,2025-44,2025-45,2025-46,2025-47,2025-48,2025-49,2025-50,2025-51,2025-52,2025-53
0,101,San José,0.001868,347692.458565,0.09434,347778.255385,347790.513802,347802.772650,347815.031931,347827.291644,...,352567.108549,352579.535762,352591.963413,352604.391503,352616.820030,352629.248995,352641.678399,352654.108241,352666.538520,352678.969238
1,102,Escazú,0.003153,69342.771863,0.09434,69371.652545,69375.779338,69379.906377,69384.033662,69388.161192,...,70991.421617,70995.644768,70999.868170,71004.091823,71008.315727,71012.539883,71016.764290,71020.988948,71025.213857,71029.439018
2,103,Desamparados,0.003087,238762.282323,0.09434,238859.651524,238873.564651,238887.478588,238901.393336,238915.308894,...,244319.247558,244333.478696,244347.710663,244361.943459,244376.177084,244390.411538,244404.646822,244418.882934,244433.119876,244447.357647
3,104,Puriscal,0.002967,38240.587051,0.09434,38255.577306,38257.719251,38259.861315,38262.003500,38264.145804,...,39095.721036,39097.910021,39100.099128,39102.288358,39104.477710,39106.667185,39108.856783,39111.046503,39113.236345,39115.426311
4,105,Tarrazú,0.001080,17842.632765,0.09434,17845.178993,17845.542770,17845.906554,17846.270345,17846.634144,...,17986.882528,17987.249193,17987.615866,17987.982546,17988.349233,17988.715929,17989.082631,17989.449341,17989.816059,17990.182784

In [ ]:
pob_prev = constants.drop(columns=["n0", "r", "t"])
pob_prev.drop(columns=semanas_2019, inplace=True)

In [ ]:
pob_prev.head()

,codigo,canton,2020-1,2020-2,2020-3,2020-4,2020-5,2020-6,2020-7,2020-8,...,2025-44,2025-45,2025-46,2025-47,2025-48,2025-49,2025-50,2025-51,2025-52,2025-53
0,101,San José,348109.384341,348121.654429,348133.924950,348146.195903,348158.467289,348170.739107,348183.011358,348195.284042,...,352567.108549,352579.535762,352591.963413,352604.391503,352616.820030,352629.248995,352641.678399,352654.108241,352666.538520,352678.969238
1,102,Escazú,69483.162181,69487.295608,69491.429281,69495.563200,69499.697365,69503.831775,69507.966432,69512.101334,...,70991.421617,70995.644768,70999.868170,71004.091823,71008.315727,71012.539883,71016.764290,71020.988948,71025.213857,71029.439018
2,103,Desamparados,239235.590543,239249.525568,239263.461404,239277.398052,239291.335512,239305.273784,239319.212867,239333.152763,...,244319.247558,244333.478696,244347.710663,244361.943459,244376.177084,244390.411538,244404.646822,244418.882934,244433.119876,244447.357647
3,104,Puriscal,38313.451927,38315.597112,38317.742417,38319.887843,38322.033388,38324.179054,38326.324839,38328.470745,...,39095.721036,39097.910021,39100.099128,39102.288358,39104.477710,39106.667185,39108.856783,39111.046503,39113.236345,39115.426311
4,105,Tarrazú,17855.003565,17855.367541,17855.731526,17856.095517,17856.459517,17856.823523,17857.187537,17857.551559,...,17986.882528,17987.249193,17987.615866,17987.982546,17988.349233,17988.715929,17989.082631,17989.449341,17989.816059,17990.182784

In [16]:
pob_prev.head()

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
codigo,101,102,103,104,105,106,107,108,109,110,...,610,611,612,613,701,702,703,704,705,706
canton,San José,Escazú,Desamparados,Puriscal,Tarrazú,Aserrí,Mora,Goicoechea,Santa Ana,Alajuelita,...,Corredores,Garabito,Monteverde,Puerto Jiménez,Limón,Pococí,Siquirres,Talamanca,Matina,Guácimo
2020-1,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,59538.680936,93044.649451,...,52032.785197,25668.495338,4732.343679,12642.628331,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
2020-2,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,59544.897083,93055.21666,...,52035.915853,25676.137705,4732.596685,12645.889676,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2020-3,348133.92495,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,59551.113878,93065.785069,...,52039.046697,25683.782347,4732.849705,12649.151863,93324.963858,149475.02389,56956.384554,43130.890582,44235.056456,55427.961628

In [17]:
pob = pd.melt(pob_prev, id_vars="semana", var_name = "canton", value_name="pob")

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['semana']"

In [ ]:
pob["week-canton"] = pob["semana"] + "-" + pob["canton"].astype(str)
pob.drop(pob=["semana", "canton"], inplace=True)