# Weekly Population Projections 2020-2025

In [101]:
import pandas as pd
import numpy as np

In [102]:
constants = pd.read_excel("../../data/raw/pob_anual.xlsx", sheet_name="constants")

In [103]:
constants.head()

   codigo        canton         r            n0        t
0       0         Total  0.003972  5.020970e+06  0.09434
1     101      San José  0.001868  3.476925e+05  0.09434
2     102        Escazú  0.003153  6.934277e+04  0.09434
3     103  Desamparados  0.003087  2.387623e+05  0.09434
4     104      Puriscal  0.002967  3.824059e+04  0.09434

In [104]:
semanas_2019 = [f"2019-{i}" for i in range(27, 54)]
semanas = semanas_2019 + [f"2020-{i}" for i in range(1, 54)]
semanas = semanas + [f"2021-{i}" for i in range(1, 54)]
semanas = semanas + [f"2022-{i}" for i in range(1, 54)]
semanas = semanas + [f"2023-{i}" for i in range(1, 54)]
semanas = semanas + [f"2024-{i}" for i in range(1, 54)]
semanas = semanas + [f"2024-{i}" for i in range(1, 54)]
semanas = semanas + [f"2025-{i}" for i in range(1, 54)]

In [105]:
for i in range(len(semanas)):
    constants[semanas[i]] = constants["n0"] * np.exp(constants["r"] * (constants["t"] + i / 53 + 2/53))

C:\Windows\Temp\ipykernel_17504\1447358950.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  constants[semanas[i]] = constants["n0"] * np.exp(constants["r"] * (constants["t"] + i / 53 + 2/53))

In [106]:
constants.head()

,codigo,canton,r,n0,t,2019-27,2019-28,2019-29,2019-30,2019-31,...,2025-44,2025-45,2025-46,2025-47,2025-48,2025-49,2025-50,2025-51,2025-52,2025-53
0,0,Total,0.003972,5.020970e+06,0.09434,5.023605e+06,5.023981e+06,5.024358e+06,5.024734e+06,5.025111e+06,...,5.171821e+06,5.172208e+06,5.172596e+06,5.172984e+06,5.173371e+06,5.173759e+06,5.174147e+06,5.174535e+06,5.174922e+06,5.175310e+06
1,101,San José,0.001868,3.476925e+05,0.09434,3.477783e+05,3.477905e+05,3.478028e+05,3.478150e+05,3.478273e+05,...,3.525671e+05,3.525795e+05,3.525920e+05,3.526044e+05,3.526168e+05,3.526292e+05,3.526417e+05,3.526541e+05,3.526665e+05,3.526790e+05
2,102,Escazú,0.003153,6.934277e+04,0.09434,6.937165e+04,6.937578e+04,6.937991e+04,6.938403e+04,6.938816e+04,...,7.099142e+04,7.099564e+04,7.099987e+04,7.100409e+04,7.100832e+04,7.101254e+04,7.101676e+04,7.102099e+04,7.102521e+04,7.102944e+04
3,103,Desamparados,0.003087,2.387623e+05,0.09434,2.388597e+05,2.388736e+05,2.388875e+05,2.389014e+05,2.389153e+05,...,2.443192e+05,2.443335e+05,2.443477e+05,2.443619e+05,2.443762e+05,2.443904e+05,2.444046e+05,2.444189e+05,2.444331e+05,2.444474e+05
4,104,Puriscal,0.002967,3.824059e+04,0.09434,3.825558e+04,3.825772e+04,3.825986e+04,3.826200e+04,3.826415e+04,...,3.909572e+04,3.909791e+04,3.910010e+04,3.910229e+04,3.910448e+04,3.910667e+04,3.910886e+04,3.911105e+04,3.911324e+04,3.911543e+04

In [107]:
pob_t = constants.drop(columns=["canton", "n0", "r", "t"])
pob_t.drop(columns=semanas_2019, inplace=True)
pob_t = pob_t.set_index("codigo")
pob_t = pob_t.transpose()

In [108]:
pob_t.columns

Index([  0, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 301, 302, 303, 304, 305,
       306, 307, 308, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 501,
       502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 601, 602, 603, 604,
       605, 606, 607, 608, 609, 610, 611, 612, 613, 701, 702, 703, 704, 705,
       706],
      dtype='int64', name='codigo')

In [109]:
pob_t.drop(columns=[612, 613], inplace=True)
pob_t.head()

codigo,0,101,102,103,104,105,106,107,108,109,...,608,609,610,611,701,702,703,704,705,706
2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,59538.680936,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,59544.897083,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,59551.113878,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,59557.331323,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,59563.549417,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [110]:
pob_t.reset_index().to_csv("../../data/raw/pob_proj_rr.csv", index=False)

In [111]:
pob = pob_t.reset_index()
pob.rename(columns={"index": "semana"}, inplace=True)

In [112]:
pob = pob.set_index("semana")

In [113]:
pob.head()

codigo,0,101,102,103,104,105,106,107,108,109,...,608,609,610,611,701,702,703,704,705,706
semana,,,,,,,,,,,,,,,,,,,,,
2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,59538.680936,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,59544.897083,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,59551.113878,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,59557.331323,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,59563.549417,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [114]:
pob.head()

codigo,0,101,102,103,104,105,106,107,108,109,...,608,609,610,611,701,702,703,704,705,706
semana,,,,,,,,,,,,,,,,,,,,,
2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,59538.680936,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,59544.897083,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,59551.113878,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,59557.331323,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,59563.549417,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [115]:
pob.rename(columns={"index": "semana"}, inplace=True)

In [116]:
pob.head()

codigo,0,101,102,103,104,105,106,107,108,109,...,608,609,610,611,701,702,703,704,705,706
semana,,,,,,,,,,,,,,,,,,,,,
2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,59538.680936,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,59544.897083,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,59551.113878,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,59557.331323,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,59563.549417,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [117]:
pob = pob.rename(columns={"index": "semana"})

In [118]:
pob.reset_index(inplace=True)

In [119]:
pob.head()

codigo,semana,0,101,102,103,104,105,106,107,108,...,608,609,610,611,701,702,703,704,705,706
0,2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
1,2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2,2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
3,2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
4,2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [120]:
pob.drop(columns = [0], inplace=True)

In [121]:
pob = pd.melt(pob, id_vars="semana", var_name = "canton", value_name="pob")

In [122]:
pob.head()

   semana canton            pob
0  2020-1    101  348109.384341
1  2020-2    101  348121.654429
2  2020-3    101  348133.924950
3  2020-4    101  348146.195903
4  2020-5    101  348158.467289

In [123]:
pob["week-canton"] = pob["semana"] + "-" + pob["canton"].astype(str)
pob.drop(columns=["semana", "canton"], inplace=True)

In [124]:
pob.head()

             pob week-canton
0  348109.384341  2020-1-101
1  348121.654429  2020-2-101
2  348133.924950  2020-3-101
3  348146.195903  2020-4-101
4  348158.467289  2020-5-101

In [100]:
pob.to_csv("../../data/clean/pob_proj.csv", index=False)