# Processing the urbanization dataset

In [25]:
import pandas as pd

In [26]:
urb = pd.read_excel("../../data/raw/grado_de_urbanidad.xlsx")

In [27]:
urb

     ID                 CANTON  URBANIZACION
0   101              SAN JOSE         Urbano
1   102       ESCAZU                  Urbano
2   103           DESAMPARADOS        Urbano
3   104  PURISCAL               Rural-urbano
4   105       TARRAZU           Rural-urbano
..  ...                    ...           ...
77  702     POCOCI                     Rural
78  703   SIQUIRRES                    Rural
79  704     TALAMANCA                  Rural
80  705   MATINA                       Rural
81  706   GUACIMO               Rural-urbano

[82 rows x 3 columns]

In [28]:
urb = urb.replace({"Urbano": 1, "Rural": 0, "Rural-urbano": 2})

In [29]:
urb

     ID                 CANTON URBANIZACION
0   101              SAN JOSE             1
1   102       ESCAZU                      1
2   103           DESAMPARADOS            1
3   104  PURISCAL                         2
4   105       TARRAZU                     2
..  ...                    ...          ...
77  702     POCOCI                        0
78  703   SIQUIRRES                       0
79  704     TALAMANCA                     0
80  705   MATINA                          0
81  706   GUACIMO                         2

[82 rows x 3 columns]

In [30]:
semanas = [f"2020-{i}" for i in range(1, 54)]
semanas = semanas + [f"2021-{i}" for i in range(1, 54)]
semanas = semanas + [f"2022-{i}" for i in range(1, 54)]
semanas = semanas + [f"2023-{i}" for i in range(1, 54)]
semanas = semanas + [f"2024-{i}" for i in range(1, 54)]
semanas = semanas + [f"2025-{i}" for i in range(1, 54)]

In [31]:
semanas

['2020-1',
 '2020-2',
 '2020-3',
 '2020-4',
 '2020-5',
 '2020-6',
 '2020-7',
 '2020-8',
 '2020-9',
 '2020-10',
 '2020-11',
 '2020-12',
 '2020-13',
 '2020-14',
 '2020-15',
 '2020-16',
 '2020-17',
 '2020-18',
 '2020-19',
 '2020-20',
 '2020-21',
 '2020-22',
 '2020-23',
 '2020-24',
 '2020-25',
 '2020-26',
 '2020-27',
 '2020-28',
 '2020-29',
 '2020-30',
 '2020-31',
 '2020-32',
 '2020-33',
 '2020-34',
 '2020-35',
 '2020-36',
 '2020-37',
 '2020-38',
 '2020-39',
 '2020-40',
 '2020-41',
 '2020-42',
 '2020-43',
 '2020-44',
 '2020-45',
 '2020-46',
 '2020-47',
 '2020-48',
 '2020-49',
 '2020-50',
 '2020-51',
 '2020-52',
 '2020-53',
 '2021-1',
 '2021-2',
 '2021-3',
 '2021-4',
 '2021-5',
 '2021-6',
 '2021-7',
 '2021-8',
 '2021-9',
 '2021-10',
 '2021-11',
 '2021-12',
 '2021-13',
 '2021-14',
 '2021-15',
 '2021-16',
 '2021-17',
 '2021-18',
 '2021-19',
 '2021-20',
 '2021-21',
 '2021-22',
 '2021-23',
 '2021-24',
 '2021-25',
 '2021-26',
 '2021-27',
 '2021-28',
 '2021-29',
 '2021-30',
 '2021-31',
 '2021-32',
 '2021-33',
 '2021-34',
 '2021-35',
 '2021-36',
 '2021-37',
 '2021-38',
 '2021-39',
 '2021-40',
 '2021-41',
 '2021-42',
 '2021-43',
 '2021-44',
 '2021-45',
 '2021-46',
 '2021-47',
 '2021-48',
 '2021-49',
 '2021-50',
 '2021-51',
 '2021-52',
 '2021-53',
 '2022-1',
 '2022-2',
 '2022-3',
 '2022-4',
 '2022-5',
 '2022-6',
 '2022-7',
 '2022-8',
 '2022-9',
 '2022-10',
 '2022-11',
 '2022-12',
 '2022-13',
 '2022-14',
 '2022-15',
 '2022-16',
 '2022-17',
 '2022-18',
 '2022-19',
 '2022-20',
 '2022-21',
 '2022-22',
 '2022-23',
 '2022-24',
 '2022-25',
 '2022-26',
 '2022-27',
 '2022-28',
 '2022-29',
 '2022-30',
 '2022-31',
 '2022-32',
 '2022-33',
 '2022-34',
 '2022-35',
 '2022-36',
 '2022-37',
 '2022-38',
 '2022-39',
 '2022-40',
 '2022-41',
 '2022-42',
 '2022-43',
 '2022-44',
 '2022-45',
 '2022-46',
 '2022-47',
 '2022-48',
 '2022-49',
 '2022-50',
 '2022-51',
 '2022-52',
 '2022-53',
 '2023-1',
 '2023-2',
 '2023-3',
 '2023-4',
 '2023-5',
 '2023-6',
 '2023-7',
 '2023-8',
 '2023-9',
 '2023-10',
 '2023-11',
 '2023-12',
 '2023-13',
 '2023-14',
 '2023-15',
 '2023-16',
 '2023-17',
 '2023-18',
 '2023-19',
 '2023-20',
 '2023-21',
 '2023-22',
 '2023-23',
 '2023-24',
 '2023-25',
 '2023-26',
 '2023-27',
 '2023-28',
 '2023-29',
 '2023-30',
 '2023-31',
 '2023-32',
 '2023-33',
 '2023-34',
 '2023-35',
 '2023-36',
 '2023-37',
 '2023-38',
 '2023-39',
 '2023-40',
 '2023-41',
 '2023-42',
 '2023-43',
 '2023-44',
 '2023-45',
 '2023-46',
 '2023-47',
 '2023-48',
 '2023-49',
 '2023-50',
 '2023-51',
 '2023-52',
 '2023-53',
 '2024-1',
 '2024-2',
 '2024-3',
 '2024-4',
 '2024-5',
 '2024-6',
 '2024-7',
 '2024-8',
 '2024-9',
 '2024-10',
 '2024-11',
 '2024-12',
 '2024-13',
 '2024-14',
 '2024-15',
 '2024-16',
 '2024-17',
 '2024-18',
 '2024-19',
 '2024-20',
 '2024-21',
 '2024-22',
 '2024-23',
 '2024-24',
 '2024-25',
 '2024-26',
 '2024-27',
 '2024-28',
 '2024-29',
 '2024-30',
 '2024-31',
 '2024-32',
 '2024-33',
 '2024-34',
 '2024-35',
 '2024-36',
 '2024-37',
 '2024-38',
 '2024-39',
 '2024-40',
 '2024-41',
 '2024-42',
 '2024-43',
 '2024-44',
 '2024-45',
 '2024-46',
 '2024-47',
 '2024-48',
 '2024-49',
 '2024-50',
 '2024-51',
 '2024-52',
 '2024-53',
 '2025-1',
 '2025-2',
 '2025-3',
 '2025-4',
 '2025-5',
 '2025-6',
 '2025-7',
 '2025-8',
 '2025-9',
 '2025-10',
 '2025-11',
 '2025-12',
 '2025-13',
 '2025-14',
 '2025-15',
 '2025-16',
 '2025-17',
 '2025-18',
 '2025-19',
 '2025-20',
 '2025-21',
 '2025-22',
 '2025-23',
 '2025-24',
 '2025-25',
 '2025-26',
 '2025-27',
 '2025-28',
 '2025-29',
 '2025-30',
 '2025-31',
 '2025-32',
 '2025-33',
 '2025-34',
 '2025-35',
 '2025-36',
 '2025-37',
 '2025-38',
 '2025-39',
 '2025-40',
 '2025-41',
 '2025-42',
 '2025-43',
 '2025-44',
 '2025-45',
 '2025-46',
 '2025-47',
 '2025-48',
 '2025-49',
 '2025-50',
 '2025-51',
 '2025-52',
 '2025-53']

In [32]:
for semana in semanas:
    urb[semana] = urb["URBANIZACION"]
urb.drop(columns=["URBANIZACION", "CANTON"], inplace=True)

C:\Windows\Temp\ipykernel_24292\2431277663.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  urb[semana] = urb["URBANIZACION"]

In [33]:
urb

,ID,2020-1,2020-2,2020-3,2020-4,2020-5,2020-6,2020-7,2020-8,2020-9,...,2025-44,2025-45,2025-46,2025-47,2025-48,2025-49,2025-50,2025-51,2025-52,2025-53
0,101,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,102,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,103,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,104,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
4,105,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,702,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,703,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
79,704,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80,705,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
81,706,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [ ]:
urb = pd.melt(urb, id_vars=["ID"], var_name="SEMANA", value_name="URBANIZACION")

In [ ]:
urb

        ID   SEMANA URBANIZACION
0      101   2020-1            1
1      102   2020-1            1
2      103   2020-1            1
3      104   2020-1            2
4      105   2020-1            2
...    ...      ...          ...
26071  702  2025-53            0
26072  703  2025-53            0
26073  704  2025-53            0
26074  705  2025-53            0
26075  706  2025-53            2

[26076 rows x 3 columns]

In [ ]:
urb