# Calculating relative risk

In [1]:
import pandas as pd

In [2]:
cases = pd.read_csv("../data/raw/cases_dengue_rr.csv")

In [3]:
cases.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,2020-1,168,22,3,0,6,0,0,1,3,...,0,49,3,19,12,5,1,9,0,0
1,2020-2,171,30,11,0,5,1,0,3,3,...,1,52,5,25,8,3,2,9,0,0
2,2020-3,160,24,15,0,3,0,0,1,1,...,2,35,0,16,3,1,2,13,0,0
3,2020-4,154,18,7,0,2,4,0,0,2,...,1,30,4,9,7,3,2,5,0,0
4,2020-5,179,9,0,0,4,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [6]:
cases.shape

(318, 93)

In [8]:
import numpy as np
pob_dummy= pd.DataFrame(np.random.randint(low = 500, high = 900, size=(318, 93)), columns=cases.columns[0:93])
pob_dummy.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,520,570,871,895,507,842,683,717,542,875,...,575,663,890,863,897,635,890,895,851,752
1,766,581,681,516,758,542,740,537,897,553,...,503,581,762,567,565,748,646,729,530,766
2,886,582,663,568,704,851,733,719,898,767,...,713,644,634,692,883,696,630,695,632,779
3,898,740,679,867,541,628,799,543,712,807,...,592,506,836,634,590,857,722,666,787,652
4,646,510,533,612,635,873,708,798,885,782,...,508,511,735,874,749,603,674,865,830,520

In [9]:
relative_risk_num = cases.iloc[:, 1:94].div(pob_dummy.iloc[:, 1:94], axis="columns")

In [10]:
relative_risk_num

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,0.294737,0.025258,0.003352,0.000000,0.007126,0.000000,0.0,0.001845,0.003429,0.000000,...,0.000000,0.073906,0.003371,0.022016,0.013378,0.007874,0.001124,0.010056,0.0,0.0
1,0.294320,0.044053,0.021318,0.000000,0.009225,0.001351,0.0,0.003344,0.005425,0.001445,...,0.001988,0.089501,0.006562,0.044092,0.014159,0.004011,0.003096,0.012346,0.0,0.0
2,0.274914,0.036199,0.026408,0.000000,0.003525,0.000000,0.0,0.001114,0.001304,0.000000,...,0.002805,0.054348,0.000000,0.023121,0.003398,0.001437,0.003175,0.018705,0.0,0.0
3,0.208108,0.026510,0.008074,0.000000,0.003185,0.005006,0.0,0.000000,0.002478,0.000000,...,0.001689,0.059289,0.004785,0.014196,0.011864,0.003501,0.002770,0.007508,0.0,0.0
4,0.350980,0.016886,0.000000,0.000000,0.004582,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.086106,0.005442,0.014874,0.021362,0.001658,0.000000,0.011561,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,0.301587,0.052928,0.052991,0.005515,0.003509,0.000000,0.0,0.001377,0.000000,0.001410,...,0.002381,0.009238,0.001712,0.006993,0.001429,0.000000,0.001266,0.001623,0.0,0.0
314,0.411215,0.063030,0.057325,0.000000,0.002628,0.000000,0.0,0.001339,0.000000,0.000000,...,0.002736,0.024499,0.001757,0.018966,0.002367,0.006861,0.005148,0.000000,0.0,0.0
315,0.260807,0.075988,0.044073,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.005272,...,0.001189,0.010870,0.003247,0.000000,0.001276,0.004505,0.002252,0.000000,0.0,0.0
316,0.162722,0.029276,0.006812,0.000000,0.001835,0.000000,0.0,0.001502,0.004724,0.000000,...,0.009820,0.005427,0.004310,0.000000,0.000000,0.001272,0.000000,0.000000,0.0,0.0
317,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [11]:
relative_risk_den = cases["0"].div(pob_dummy["0"])

In [14]:
relative_risk_den.head()

0    0.294737
1    0.294320
2    0.274914
3    0.208108
4    0.350980
Name: 0, dtype: float64

In [15]:
relative_risk = relative_risk_num.div(relative_risk_den.values, axis=0)

In [ ]:
relative_risk["semana"] = cases["semana"]

In [16]:
relative_risk

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,1.0,0.085698,0.011373,0.000000,0.024177,0.000000,0.0,0.006260,0.011633,0.000000,...,0.000000,0.250754,0.011437,0.074698,0.045389,0.026715,0.003812,0.034118,0.0,0.0
1,1.0,0.149677,0.072431,0.000000,0.031344,0.004591,0.0,0.011363,0.018432,0.004910,...,0.006755,0.304094,0.022294,0.149809,0.048108,0.013627,0.010519,0.041946,0.0,0.0
2,1.0,0.131674,0.096061,0.000000,0.012823,0.000000,0.0,0.004051,0.004743,0.000000,...,0.010203,0.197690,0.000000,0.084104,0.012358,0.005226,0.011548,0.068040,0.0,0.0
3,1.0,0.127384,0.038796,0.000000,0.015303,0.024056,0.0,0.000000,0.011909,0.000000,...,0.008117,0.284893,0.022991,0.068213,0.057011,0.016821,0.013311,0.036075,0.0,0.0
4,1.0,0.048110,0.000000,0.000000,0.013055,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.245329,0.015506,0.042379,0.060863,0.004725,0.000000,0.032938,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,1.0,0.175498,0.175709,0.018286,0.011634,0.000000,0.0,0.004567,0.000000,0.004677,...,0.007895,0.030631,0.005678,0.023187,0.004737,0.000000,0.004197,0.005383,0.0,0.0
314,1.0,0.153278,0.139404,0.000000,0.006391,0.000000,0.0,0.003255,0.000000,0.000000,...,0.006653,0.059577,0.004274,0.046121,0.005756,0.016685,0.012519,0.000000,0.0,0.0
315,1.0,0.291357,0.168987,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.020216,...,0.004559,0.041677,0.012449,0.000000,0.004891,0.017271,0.008636,0.000000,0.0,0.0
316,1.0,0.179913,0.041863,0.000000,0.011276,0.000000,0.0,0.009227,0.029034,0.000000,...,0.060348,0.033354,0.026489,0.000000,0.000000,0.007819,0.000000,0.000000,0.0,0.0
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
relative_risk = pd.melt(relative_risk , id_vars="semana", var_name = "canton", value_name="casos")
relative_risk ["week-canton"] = relative_risk ["semana"] + "-" + relative_risk ["canton"].astype(str)
relative_risk .drop(columns=["semana", "canton"], inplace=True)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['semana']"

In [3]:
relative_risk.head()

NameError: name 'relative_risk' is not defined

In [12]:
relative_risk.to_csv("../data/clean/relative_risk.csv", index=False)