# Calculating relative risk

In [1]:
import pandas as pd

In [2]:
cases = pd.read_csv("../data/clean/casos_dengue.csv")

In [3]:
cases.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,1,168,22,3,0,6,0,0,1,3,...,0,49,3,19,12,5,1,9,0,0
1,2,171,30,11,0,5,1,0,3,3,...,1,52,5,25,8,3,2,9,0,0
2,3,160,24,15,0,3,0,0,1,1,...,2,35,0,16,3,1,2,13,0,0
3,4,154,18,7,0,2,4,0,0,2,...,1,30,4,9,7,3,2,5,0,0
4,5,179,9,0,0,4,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [4]:
cases.shape

(318, 93)

In [15]:
import numpy as np
pob_dummy= pd.DataFrame(np.random.randint(low = 500, high = 900, size=(318, 93)), columns=cases.columns[0:93])
pob_dummy.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,759,706,769,890,730,509,856,811,648,669,...,827,781,518,688,853,833,513,822,591,638
1,517,852,650,577,710,735,523,872,663,672,...,545,654,869,630,581,508,514,823,611,709
2,618,749,568,528,707,746,552,759,852,603,...,686,673,708,818,546,763,795,889,809,748
3,647,864,864,506,630,739,535,820,808,520,...,512,836,884,637,894,847,621,637,557,845
4,832,601,608,858,588,505,837,808,659,733,...,609,700,717,665,822,663,569,828,763,629

In [32]:
relative_risk_num = cases.iloc[:, 1:94].div(pob_dummy.iloc[:, 1:94], axis="columns")

In [33]:
relative_risk_num

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,0.237960,0.028609,0.003371,0.000000,0.011788,0.000000,0.0,0.001543,0.004484,0.000000,...,0.000000,0.062740,0.005792,0.027616,0.014068,0.006002,0.001949,0.010949,0.0,0.0
1,0.200704,0.046154,0.019064,0.000000,0.006803,0.001912,0.0,0.004525,0.004464,0.001739,...,0.001835,0.079511,0.005754,0.039683,0.013769,0.005906,0.003891,0.010936,0.0,0.0
2,0.213618,0.042254,0.028409,0.000000,0.004021,0.000000,0.0,0.001174,0.001658,0.000000,...,0.002915,0.052006,0.000000,0.019560,0.005495,0.001311,0.002516,0.014623,0.0,0.0
3,0.178241,0.020833,0.013834,0.000000,0.002706,0.007477,0.0,0.000000,0.003846,0.000000,...,0.001953,0.035885,0.004525,0.014129,0.007830,0.003542,0.003221,0.007849,0.0,0.0
4,0.297837,0.014803,0.000000,0.000000,0.007921,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.062857,0.005579,0.019549,0.019465,0.001508,0.000000,0.012077,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,0.335689,0.054210,0.038847,0.004967,0.005607,0.000000,0.0,0.001506,0.000000,0.001229,...,0.002339,0.011799,0.001152,0.005952,0.001608,0.000000,0.001266,0.001385,0.0,0.0
314,0.250000,0.064757,0.069364,0.000000,0.003643,0.000000,0.0,0.001456,0.000000,0.000000,...,0.002721,0.035200,0.001508,0.016949,0.002554,0.005242,0.006981,0.000000,0.0,0.0
315,0.223457,0.061958,0.044207,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.005445,...,0.001230,0.012903,0.003817,0.000000,0.001767,0.005725,0.002692,0.000000,0.0,0.0
316,0.218254,0.022093,0.007364,0.000000,0.001401,0.000000,0.0,0.001385,0.004261,0.000000,...,0.009615,0.007890,0.003667,0.000000,0.000000,0.001773,0.000000,0.000000,0.0,0.0
317,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [34]:
relative_risk_den = cases["0"].div(pob_dummy["0"])

In [35]:
relative_risk_den.head()

0    0.237960
1    0.200704
2    0.213618
3    0.178241
4    0.297837
Name: 0, dtype: float64

In [41]:
relative_risk = relative_risk_num.div(relative_risk_den.values, axis=0)

In [42]:
relative_risk

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,1.0,0.120224,0.014165,0.000000,0.049537,0.000000,0.0,0.006485,0.018845,0.000000,...,0.000000,0.263658,0.024338,0.116054,0.059119,0.025224,0.008192,0.046011,0.0,0.0
1,1.0,0.229960,0.094986,0.000000,0.033894,0.009527,0.0,0.022545,0.022243,0.008665,...,0.009142,0.396159,0.028668,0.197717,0.068605,0.029424,0.019387,0.054486,0.0,0.0
2,1.0,0.197799,0.132990,0.000000,0.018825,0.000000,0.0,0.005494,0.007763,0.000000,...,0.013648,0.243453,0.000000,0.091565,0.025721,0.006135,0.011777,0.068455,0.0,0.0
3,1.0,0.116883,0.077614,0.000000,0.015184,0.041947,0.0,0.000000,0.021578,0.000000,...,0.010958,0.201330,0.025386,0.079268,0.043929,0.019872,0.018069,0.044038,0.0,0.0
4,1.0,0.049700,0.000000,0.000000,0.026594,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.211045,0.018731,0.065636,0.065354,0.005064,0.000000,0.040550,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,1.0,0.161488,0.115724,0.014796,0.016704,0.000000,0.0,0.004486,0.000000,0.003660,...,0.006968,0.035150,0.003432,0.017732,0.004789,0.000000,0.003771,0.004126,0.0,0.0
314,1.0,0.259029,0.277457,0.000000,0.014572,0.000000,0.0,0.005822,0.000000,0.000000,...,0.010884,0.140800,0.006033,0.067797,0.010217,0.020970,0.027923,0.000000,0.0,0.0
315,1.0,0.277270,0.197834,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.024366,...,0.005504,0.057744,0.017081,0.000000,0.007907,0.025621,0.012046,0.000000,0.0,0.0
316,1.0,0.101226,0.033739,0.000000,0.006417,0.000000,0.0,0.006346,0.019525,0.000000,...,0.044056,0.036148,0.016804,0.000000,0.000000,0.008124,0.000000,0.000000,0.0,0.0
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# relative_risk.to_csv("../data/clean/relative_risk.csv", index=False)