# Calculating relative risk

In [1]:
import pandas as pd
import numpy as np

In [2]:
cases = pd.read_csv("../data/raw/cases_dengue_rr.csv")

In [3]:
cases.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,2020-1,168,22,3,0,6,0,0,1,3,...,0,49,3,19,12,5,1,9,0,0
1,2020-2,171,30,11,0,5,1,0,3,3,...,1,52,5,25,8,3,2,9,0,0
2,2020-3,160,24,15,0,3,0,0,1,1,...,2,35,0,16,3,1,2,13,0,0
3,2020-4,154,18,7,0,2,4,0,0,2,...,1,30,4,9,7,3,2,5,0,0
4,2020-5,179,9,0,0,4,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [4]:
cases.shape

(318, 93)

In [5]:
cases.drop(columns=["1"], inplace=True)

In [6]:
cases.head()

,semana,0,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,2020-1,168,3,0,6,0,0,1,3,0,...,0,49,3,19,12,5,1,9,0,0
1,2020-2,171,11,0,5,1,0,3,3,1,...,1,52,5,25,8,3,2,9,0,0
2,2020-3,160,15,0,3,0,0,1,1,0,...,2,35,0,16,3,1,2,13,0,0
3,2020-4,154,7,0,2,4,0,0,2,0,...,1,30,4,9,7,3,2,5,0,0
4,2020-5,179,0,0,4,0,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [7]:
cases.drop(columns=["2", "3", "4", "5", "6", "7", '99', '98'], inplace=True)

In [8]:
cases.head()

,semana,0,101,102,103,104,105,106,107,108,...,608,609,610,611,701,702,703,704,705,706
0,2020-1,168,3,0,6,0,0,1,3,0,...,0,0,2,0,3,19,12,5,1,9
1,2020-2,171,11,0,5,1,0,3,3,1,...,0,1,2,1,5,25,8,3,2,9
2,2020-3,160,15,0,3,0,0,1,1,0,...,1,0,2,2,0,16,3,1,2,13
3,2020-4,154,7,0,2,4,0,0,2,0,...,0,0,8,1,4,9,7,3,2,5
4,2020-5,179,0,0,4,0,0,0,0,0,...,0,2,3,0,4,13,16,1,0,10

In [9]:
cases.shape

(318, 84)

In [10]:
pob = pd.read_csv("../data/raw/pob_proj_rr.csv")

In [11]:
pob.head()

,index,0,101,102,103,104,105,106,107,108,...,608,609,610,611,701,702,703,704,705,706
0,2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,...,36391.733531,20962.773682,52032.785197,25668.495338,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
1,2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,...,36389.695674,20966.563094,52035.915853,25676.137705,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2,2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,...,36387.657930,20970.353191,52039.046697,25683.782347,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
3,2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,...,36385.620301,20974.143974,52042.177730,25691.429265,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
4,2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,...,36383.582786,20977.935441,52045.308951,25699.078460,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [12]:
pob.shape

(318, 84)

In [13]:
cases.tail()

,semana,0,101,102,103,104,105,106,107,108,...,608,609,610,611,701,702,703,704,705,706
313,2025-49,190,31,3,3,0,0,1,0,1,...,0,0,1,2,1,4,1,0,1,1
314,2025-50,220,36,0,2,0,0,1,0,0,...,0,0,0,2,1,11,2,4,4,0
315,2025-51,181,29,0,0,0,0,0,0,3,...,0,2,0,1,2,0,1,3,2,0
316,2025-52,110,5,0,1,0,0,1,3,0,...,0,6,1,6,3,0,0,1,0,0
317,2025-53,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
relative_risk_num = cases.div(pob, axis="columns")

In [15]:
relative_risk_num.tail()

,0,101,102,103,104,105,106,107,108,109,...,610,611,701,702,703,704,705,706,index,semana
313,0.000037,0.000088,0.000042,0.000012,0.0,0.0,0.000016,0.000000,0.000007,0.000065,...,0.000019,0.000071,0.000011,0.000026,0.000018,0.000000,0.000022,0.000017,NaN,NaN
314,0.000043,0.000102,0.000000,0.000008,0.0,0.0,0.000016,0.000000,0.000000,0.000114,...,0.000000,0.000071,0.000011,0.000071,0.000035,0.000088,0.000089,0.000000,NaN,NaN
315,0.000035,0.000082,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000022,0.000098,...,0.000000,0.000035,0.000022,0.000000,0.000018,0.000066,0.000044,0.000000,NaN,NaN
316,0.000021,0.000014,0.000000,0.000004,0.0,0.0,0.000016,0.000105,0.000000,0.000000,...,0.000019,0.000213,0.000032,0.000000,0.000000,0.000022,0.000000,0.000000,NaN,NaN
317,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN

In [16]:
relative_risk_den = cases["0"].div(pob["0"], axis="index")

In [17]:
relative_risk_den.head()

0    0.000033
1    0.000034
2    0.000032
3    0.000031
4    0.000036
Name: 0, dtype: float64

In [18]:
relative_risk = relative_risk_num.div(relative_risk_den, axis="index")

In [19]:
relative_risk.tail()

,0,101,102,103,104,105,106,107,108,109,...,610,611,701,702,703,704,705,706,index,semana
313,1.0,2.388814,1.149431,0.333968,0.0,0.0,0.433593,0.000000,0.194477,1.763587,...,0.511531,1.925268,0.293765,0.702115,0.474694,0.000000,0.600604,0.467645,NaN,NaN
314,1.0,2.395914,0.000000,0.192288,0.0,0.0,0.374479,0.000000,0.000000,2.665343,...,0.000000,1.662361,0.253734,1.667469,0.819980,2.062377,2.074832,0.000000,NaN,NaN
315,1.0,2.346001,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.612474,2.776755,...,0.000000,1.010050,0.616879,0.000000,0.498363,1.879894,1.260958,0.000000,NaN,NaN
316,1.0,0.665585,0.000000,0.192294,0.0,0.0,0.749007,4.899799,0.000000,0.000000,...,0.883593,9.969722,1.522737,0.000000,0.000000,1.030999,0.000000,0.000000,NaN,NaN
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
relative_risk.drop(columns=["0", "index"], inplace=True)

In [21]:
relative_risk["semana"] = cases["semana"]

In [22]:
relative_risk

,101,102,103,104,105,106,107,108,109,110,...,609,610,611,701,702,703,704,705,706,semana
0,0.258220,0.000000,0.751468,0.000000,0.0,0.485391,3.171912,0.000000,0.503252,1.288112,...,0.000000,1.151696,0.000000,0.963115,3.809453,6.312953,3.474652,0.677448,4.866594,2020-1
1,0.930234,0.000000,0.615247,0.768343,0.0,1.430673,3.116376,0.214348,0.494409,1.265464,...,1.404117,1.131508,1.146571,1.577204,4.924344,4.135068,2.048028,1.331137,4.780877,2020-2
2,1.355764,0.000000,0.394534,0.000000,0.0,0.509694,1.110249,0.000000,0.528384,0.000000,...,0.000000,1.209317,2.450250,0.000000,3.368144,1.657365,0.729543,1.422665,7.379956,2020-3
3,0.657366,0.000000,0.273275,3.412769,0.0,0.000000,2.307094,0.000000,1.097908,0.000000,...,0.000000,5.025805,1.272573,1.401355,1.968333,4.018115,2.273692,1.478106,2.948825,2020-4
4,0.000000,0.000000,0.470224,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.302192,...,2.681876,1.621478,0.000000,1.205767,2.445983,7.902056,0.651986,0.000000,5.073596,2020-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,2.388814,1.149431,0.333968,0.000000,0.0,0.433593,0.000000,0.194477,1.763587,0.843957,...,0.000000,0.511531,1.925268,0.293765,0.702115,0.474694,0.000000,0.600604,0.467645,2025-49
314,2.395914,0.000000,0.192288,0.000000,0.0,0.374479,0.000000,0.000000,2.665343,0.485896,...,0.000000,0.000000,1.662361,0.253734,1.667469,0.819980,2.062377,2.074832,0.000000,2025-50
315,2.346001,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.612474,2.776755,2.362274,...,2.566384,0.000000,1.010050,0.616879,0.000000,0.498363,1.879894,1.260958,0.000000,2025-51
316,0.665585,0.000000,0.192294,0.000000,0.0,0.749007,4.899799,0.000000,0.000000,2.915149,...,12.667263,0.883593,9.969722,1.522737,0.000000,0.000000,1.030999,0.000000,0.000000,2025-52
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-53

In [23]:
relative_risk = pd.melt(relative_risk , id_vars="semana", var_name = "canton", value_name="rr")
relative_risk ["week-canton"] = relative_risk ["semana"] + "-" + relative_risk ["canton"].astype(str)
relative_risk .drop(columns=["semana", "canton"], inplace=True)

In [46]:
umbral_bajo = np.nanpercentile(relative_risk["rr"], q = 30)
umbral_medio = np.nanpercentile(relative_risk["rr"], q = 70)
umbral_alto = max(relative_risk["rr"])

relative_risk["clasi_rr"] = np.where(relative_risk["rr"] <= umbral_bajo, "Bajo", np.where(relative_risk["rr"] >= umbral_medio, "Alto", "Medio"))

In [25]:
relative_risk.head()

         rr week-canton clasi_rr
0  0.258220  2020-1-101     Bajo
1  0.930234  2020-2-101     Bajo
2  1.355764  2020-3-101     Bajo
3  0.657366  2020-4-101     Bajo
4  0.000000  2020-5-101     Bajo

In [49]:
relative_risk.tail()

             rr  week-canton clasi_rr
26071  0.467645  2025-49-706    Medio
26072  0.000000  2025-50-706     Bajo
26073  0.000000  2025-51-706     Bajo
26074  0.000000  2025-52-706     Bajo
26075       NaN  2025-53-706    Medio

In [50]:
relative_risk.to_csv("../data/clean/relative_risk.csv", index=False)