# Calculating relative risk

In [56]:
import pandas as pd

In [57]:
cases = pd.read_csv("../data/raw/cases_dengue_rr.csv")

In [58]:
cases.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,2020-1,168,22,3,0,6,0,0,1,3,...,0,49,3,19,12,5,1,9,0,0
1,2020-2,171,30,11,0,5,1,0,3,3,...,1,52,5,25,8,3,2,9,0,0
2,2020-3,160,24,15,0,3,0,0,1,1,...,2,35,0,16,3,1,2,13,0,0
3,2020-4,154,18,7,0,2,4,0,0,2,...,1,30,4,9,7,3,2,5,0,0
4,2020-5,179,9,0,0,4,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [59]:
cases.shape

(318, 93)

In [60]:
cases.drop(columns=["1"], inplace=True)

In [61]:
cases.head()

,semana,0,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,2020-1,168,3,0,6,0,0,1,3,0,...,0,49,3,19,12,5,1,9,0,0
1,2020-2,171,11,0,5,1,0,3,3,1,...,1,52,5,25,8,3,2,9,0,0
2,2020-3,160,15,0,3,0,0,1,1,0,...,2,35,0,16,3,1,2,13,0,0
3,2020-4,154,7,0,2,4,0,0,2,0,...,1,30,4,9,7,3,2,5,0,0
4,2020-5,179,0,0,4,0,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [62]:
pob = pd.read_csv("../data/raw/pob_proj_rr.csv")

In [63]:
pob.head()

,index,0,101,102,103,104,105,106,107,108,...,610,611,612,613,701,702,703,704,705,706
0,2020-1,5.033780e+06,348109.384341,69483.162181,239235.590543,38313.451927,17855.003565,61729.540459,28339.039089,137337.846168,...,52032.785197,25668.495338,4732.343679,12642.628331,93331.417821,149443.130319,56955.228239,43116.508765,44229.179531,55411.809538
1,2020-2,5.034157e+06,348121.654429,69487.295608,239249.525568,38315.597112,17855.367541,61732.152649,28340.142649,137344.583388,...,52035.915853,25676.137705,4732.596685,12645.889676,93328.190784,149459.076254,56955.806394,43123.699074,44232.117896,55419.884994
2,2020-3,5.034534e+06,348133.924950,69491.429281,239263.461404,38317.742417,17855.731526,61734.764949,28341.246252,137351.320939,...,52039.046697,25683.782347,4732.849705,12649.151863,93324.963858,149475.023890,56956.384554,43130.890582,44235.056456,55427.961628
3,2020-4,5.034912e+06,348146.195903,69495.563200,239277.398052,38319.887843,17856.095517,61737.377359,28342.349898,137358.058820,...,52042.177730,25691.429265,4733.102738,12652.414891,93321.737043,149490.973228,56956.962721,43138.083290,44237.995212,55436.039438
4,2020-5,5.035289e+06,348158.467289,69499.697365,239291.335512,38322.033388,17856.459517,61739.989880,28343.453587,137364.797031,...,52045.308951,25699.078460,4733.355785,12655.678761,93318.510341,149506.924267,56957.540894,43145.277197,44240.934163,55444.118426

In [69]:
relative_risk_num = cases.iloc[:, 0:93].div(pob.iloc[:, 0:93], axis="columns")

In [70]:
relative_risk_num

,0,101,102,103,104,105,106,107,108,109,...,701,702,703,704,705,706,98,99,index,semana
0,0.000033,0.000009,0.000000,0.000025,0.000000,0.0,0.000016,0.000106,0.000000,0.000017,...,0.000032,0.000127,0.000211,0.000116,0.000023,0.000162,NaN,NaN,NaN,NaN
1,0.000034,0.000032,0.000000,0.000021,0.000026,0.0,0.000049,0.000106,0.000007,0.000017,...,0.000054,0.000167,0.000140,0.000070,0.000045,0.000162,NaN,NaN,NaN,NaN
2,0.000032,0.000043,0.000000,0.000013,0.000000,0.0,0.000016,0.000035,0.000000,0.000017,...,0.000000,0.000107,0.000053,0.000023,0.000045,0.000235,NaN,NaN,NaN,NaN
3,0.000031,0.000020,0.000000,0.000008,0.000104,0.0,0.000000,0.000071,0.000000,0.000034,...,0.000043,0.000060,0.000123,0.000070,0.000045,0.000090,NaN,NaN,NaN,NaN
4,0.000036,0.000000,0.000000,0.000017,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000043,0.000087,0.000281,0.000023,0.000000,0.000180,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,0.000037,0.000088,0.000042,0.000012,0.000000,0.0,0.000016,0.000000,0.000007,0.000065,...,0.000011,0.000026,0.000017,0.000000,0.000022,0.000017,NaN,NaN,NaN,NaN
314,0.000043,0.000102,0.000000,0.000008,0.000000,0.0,0.000016,0.000000,0.000000,0.000113,...,0.000011,0.000071,0.000035,0.000087,0.000088,0.000000,NaN,NaN,NaN,NaN
315,0.000035,0.000082,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000021,0.000097,...,0.000022,0.000000,0.000017,0.000065,0.000044,0.000000,NaN,NaN,NaN,NaN
316,0.000021,0.000014,0.000000,0.000004,0.000000,0.0,0.000016,0.000104,0.000000,0.000000,...,0.000033,0.000000,0.000000,0.000022,0.000000,0.000000,NaN,NaN,NaN,NaN
317,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN

In [71]:
relative_risk_den = cases.div(pob.iloc[:, 1:93], axis="columns")

In [81]:
relative_risk_den.head()

,0,101,102,103,104,105,106,107,108,109,...,7,701,702,703,704,705,706,98,99,semana
0,0.000033,0.000009,0.0,0.000025,0.000000,0.0,0.000016,0.000106,0.000000,0.000017,...,NaN,0.000032,0.000127,0.000211,0.000116,0.000023,0.000162,NaN,NaN,NaN
1,0.000034,0.000032,0.0,0.000021,0.000026,0.0,0.000049,0.000106,0.000007,0.000017,...,NaN,0.000054,0.000167,0.000140,0.000070,0.000045,0.000162,NaN,NaN,NaN
2,0.000032,0.000043,0.0,0.000013,0.000000,0.0,0.000016,0.000035,0.000000,0.000017,...,NaN,0.000000,0.000107,0.000053,0.000023,0.000045,0.000235,NaN,NaN,NaN
3,0.000031,0.000020,0.0,0.000008,0.000104,0.0,0.000000,0.000071,0.000000,0.000034,...,NaN,0.000043,0.000060,0.000123,0.000070,0.000045,0.000090,NaN,NaN,NaN
4,0.000036,0.000000,0.0,0.000017,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000043,0.000087,0.000281,0.000023,0.000000,0.000180,NaN,NaN,NaN

In [84]:
relative_risk_den.drop(columns=["2", "3", "4", "5", "6", "7"], inplace=True)

In [87]:
relative_risk = relative_risk_num.iloc[:, :relative_risk_den.shape[1]].div(relative_risk_den.values, axis=0)

In [88]:
relative_risk.head()

,0,101,102,103,104,105,106,107,108,109,...,608,609,610,611,612,613,7,701,702,703
0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,...,NaN,0.000000,0.302326,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,...,NaN,0.890257,0.229778,0.277280,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,...,NaN,NaN,0.359045,1.478401,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,...,NaN,0.000000,2.553330,0.316709,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.224206,0.662915,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
relative_risk["semana"] = cases["semana"]

In [16]:
relative_risk

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,1.0,0.085698,0.011373,0.000000,0.024177,0.000000,0.0,0.006260,0.011633,0.000000,...,0.000000,0.250754,0.011437,0.074698,0.045389,0.026715,0.003812,0.034118,0.0,0.0
1,1.0,0.149677,0.072431,0.000000,0.031344,0.004591,0.0,0.011363,0.018432,0.004910,...,0.006755,0.304094,0.022294,0.149809,0.048108,0.013627,0.010519,0.041946,0.0,0.0
2,1.0,0.131674,0.096061,0.000000,0.012823,0.000000,0.0,0.004051,0.004743,0.000000,...,0.010203,0.197690,0.000000,0.084104,0.012358,0.005226,0.011548,0.068040,0.0,0.0
3,1.0,0.127384,0.038796,0.000000,0.015303,0.024056,0.0,0.000000,0.011909,0.000000,...,0.008117,0.284893,0.022991,0.068213,0.057011,0.016821,0.013311,0.036075,0.0,0.0
4,1.0,0.048110,0.000000,0.000000,0.013055,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.245329,0.015506,0.042379,0.060863,0.004725,0.000000,0.032938,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,1.0,0.175498,0.175709,0.018286,0.011634,0.000000,0.0,0.004567,0.000000,0.004677,...,0.007895,0.030631,0.005678,0.023187,0.004737,0.000000,0.004197,0.005383,0.0,0.0
314,1.0,0.153278,0.139404,0.000000,0.006391,0.000000,0.0,0.003255,0.000000,0.000000,...,0.006653,0.059577,0.004274,0.046121,0.005756,0.016685,0.012519,0.000000,0.0,0.0
315,1.0,0.291357,0.168987,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.020216,...,0.004559,0.041677,0.012449,0.000000,0.004891,0.017271,0.008636,0.000000,0.0,0.0
316,1.0,0.179913,0.041863,0.000000,0.011276,0.000000,0.0,0.009227,0.029034,0.000000,...,0.060348,0.033354,0.026489,0.000000,0.000000,0.007819,0.000000,0.000000,0.0,0.0
317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
relative_risk = pd.melt(relative_risk , id_vars="semana", var_name = "canton", value_name="casos")
relative_risk ["week-canton"] = relative_risk ["semana"] + "-" + relative_risk ["canton"].astype(str)
relative_risk .drop(columns=["semana", "canton"], inplace=True)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['semana']"

In [3]:
relative_risk.head()

NameError: name 'relative_risk' is not defined

In [12]:
relative_risk.to_csv("../data/clean/relative_risk.csv", index=False)